services:

  postgres:
    image: postgres:16-alpine
    container_name: devops-platform-postgres

    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: performance_db

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - platform-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d performance_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: devops-platform-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - platform-net

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  postgres-data:
  redis-data:


networks:
  platform-net:
    driver: bridge
