{{- if eq .Values.strategy.type "blueGreen" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.strategy.blueGreen.activeService }}
  labels:
    app: performance-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: performance-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.strategy.blueGreen.previewService }}
  labels:
    app: performance-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: performance-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

{{- end }}
