apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-platform-config
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
