apiVersion: v1
kind: Secret
metadata:
  name: performance-platform-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
