{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: performance-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: performance-api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - performance-platform
{{- end }}
