replicaCount: 2

image:
  repository: ghcr.io/rithuraj6/devops-perfomance-api
  tag: "17"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

config:
  appEnv: production
  databaseHost: performance-postgresql
  databasePort: "5432"
  databaseName: performance_db
  databaseUser: app_user
  redisHost: performance-redis-master
  redisPort: "6379"

secret:
  databasePassword: app_password
  redisPassword: redis_password

serviceMonitor:
  enabled: true
  interval: 15s


ingress:
  enabled: false
  className: nginx
  host: performance.local
  path: /

istio:
  enabled: true
  gateway:
    name: performance-api-gateway
    host: performance.local
    port: 80
  virtualService:
    name: performance-api
    routeName: primary

strategy:
  type: blueGreen

  canary:
    steps:
      - setWeight: 10
      - pause:
          duration: 30s
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 75
      - pause:
          duration: 60s
      - setWeight: 100

  blueGreen:
    activeService: performance-api-active
    previewService: performance-api-preview
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 30
