apiVersion: v1
kind: Secret
metadata:
  name: performance-platform-secret
  namespace: performance-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://<username>:<password>@postgres:5432/<database>"
